use aoc::error::Result;

fn main() -> Result<()> {
    Ok(())
}
